#!/bin/bash

# check if the script is run as root
# id command provides user and group information, including UID, GID and supplementary group memberships
# id -u print only the effective user ID
# Reference: id man page
# ! [ $(id -u) = 0 ] checks if the user ID is not 0, i.e., the script is not run as root
# Reference: https://www.baeldung.com/linux/check-script-run-root
#
if ! [ $(id -u) = 0 ]; then
  echo "Please run this script as root."
  exit 1
fi


# this scripts accepts 2 options p and s
# p option executes the install-packages script
# s option executes the create-symbolic-links script
# If an invalid option is provided, the user is notified
# 
while getopts "ps" opt; do
	case "${opt}" in
		p)
			./install-packages
			;;
		s)
			./create-symbolic-links
			;;
		?)
			echo "Invalid option! Use -p to install packages and -s to create symbolic links!"
			exit 1
			;;
	esac
done

